# CC3001 Otoño 2021 Tarea 2

## Shellsort

### Profesores
Sección 1 Iván Sipirán •
Sección 2 Patricio Poblete •
Sección 3 Nelson Baloian


El objetivo de esta tarea es que usted implemente el algoritmo de ordenación Shellsort.

Para describir cómo funciona Shellsort definamos un arreglo "$d$-ordenado" (donde $d$ es un entero mayor o igual a 1) como un arreglo en que cada elemento está ordenado respecto de sus vecinos que están a $d$ casilleros de distancia. Por ejemplo, en el siguiente diagrama se muestran un arreglo antes y después de ser "3-ordenado", destacando en distintos colores las las subsecuencias que se forman al considerar elementos que están a distancia 3:

Antes:

![shellsort1](https://github.com/ppoblete/CC3001-2020-2-Tareas/blob/master/shellsort1.png?raw=1)

Después:

![shellsort2](https://github.com/ppoblete/CC3001-2020-2-Tareas/blob/master/shellsort2.png?raw=1)

Noten que el caso particular de un arreglo "1-ordenado" (caso $d=1$) sería lo mismo que un arreglo ordenado.

El algoritmo Shellsort consiste en hacer una secuencia de pasadas $d$-ordenando el arreglo, cada vez con un valor diferente de $d$, siendo la última siempre con $d=1$.

Para hacer una pasada de Shellsort elegimos un valor de $d$ y luego aplicamos una versión modificada de ordenación por inserción. La modificación consiste en que la función ``insertar(a,k)`` compara con el elemento $d$ casilleros más atrás, en lugar de hacerlo con el que está uno más atrás.

Para ordenar el arreglo completo, Shellsort hace una secuencia de pasadas, con un conjunto decreciente de valores $d_k,d_{k-1}, \ldots,d_1$, con $d_1=1$. Esto último asegura que el arreglo quede finalmente ordenado, pero las pasadas anteriores contribuyen a acelerar el proceso, porque hay un teorema (que no les pedimos demostrar) que dice que si un arreglo que ya estaba $i$-ordenado se $j$-ordena, el arreglo resultante sigue estando $i$-ordenado. Esto es, una pasada no echa a perder lo que han hecho las anteriores.

# Recuerdo de la ordenación por inserción

Recuerde que la ordenación por inserción está implementada en el apunte de la manera siguiente:

In [ ]:
def ordena_insercion(a):
    """Ordena el arreglo a por inserción"""
    n=len(a)
    for k in range(0,n):
        insertar(a,k)
        
def insertar(a, k):
    """
    Inserta a[k] entre los elementos anteriores
    preservando el orden ascendente (versión 2)
    """
    b=a[k] # b almacena transitoriamente al elemento a[k]
    j=k # señala la posición del lugar "vacío"
    while j>0 and b<a[j-1]:
        a[j]=a[j-1]
        j-=1
    a[j]=b

Probemos esto para asegurarnos que funcione bien:

In [ ]:
import numpy as np

def verifica_d_ordenado(a,d):
    for i in range(0,len(a)-d):
        assert a[i]<=a[i+d]
    print("Arreglo "+str(d)+"-ordenado OK.")
        
A = np.array([46,35,95,21,82,70,72,56,64,50])
ordena_insercion(A)
print(A)
verifica_d_ordenado(A,1)

[21 35 46 50 56 64 70 72 82 95]
Arreglo 1-ordenado OK.


---
# Lo que usted tiene que hacer:

## 1) Programar una $d$-ordenación

Modifique el código anterior para que $d$-ordene el arreglo, para un valor de $d$ dado. Para esto, escriba el código de la función ``d_insertar`` en el espacio provisto:

In [ ]:
#Kevin Alexis Iturra Carreño
def d_ordena_insercion(a,d):
    n=len(a)
    for k in range(0,n):
        d_insertar(a,k,d)
        
def d_insertar(a,k,d):
  # escriba aquí el código modificado de la función insertar
  # para que haga una d-inserción en lugar de una inserción
  # Tomamos todos los números que estén entre k+la distancia d y el largo de la lista, recordando que k varía entre 0 y el largo de la lista (len(a))
  for i in range(k+d,len(a)):
    # b almacena transitoriamente al elemento a[k]
    b=a[i]
    # Señala la posición del lugar "vacío"
    j=i
    # Aquí, mientras nuestro lugar de "Vacio" sea mayor a cero y
    # a la vez la variable que almacena nuestro elemento sea menor que el elemento de la posición j-d de la lista
    while j>0 and b<a[j-d]:
      #se reemplaza de posición el a[j- la distancia d] con el a[j]
      a[j]=a[j-d]
      #a la variable j se le resta la cantidad d para que
      j-=d
    #por último reemplazamos a b como a[j]
    a[j]=b

Pruebe aquí que su algoritmo $3$-ordena correctamente:

In [ ]:
A = np.array([46,35,95,21,82,70,72,56,64,50])
d_ordena_insercion(A,3)
print(A)
verifica_d_ordenado(A,3)

[21 35 64 46 56 70 50 82 95 72]
Arreglo 3-ordenado OK.


## 2) Programar Shellsort

Con esto ya estamos listos para programar Shellsort, haciendo una secuencia de pasadas, variando el valor de $d$ y terminando con $d=1$.Hay muchas formas conocidas de generar la secuencia de valores de $d$, con variados niveles de eficiencia. A continuación, programe Shellsort usando una secuencia decreciente de valores de la forma $d_k=2^k-1$, esto es: $\ldots, 63, 31, 15, 7, 3, 1$. Se sabe que esta secuencia hace que Shellsort funcione en tiempo $\Theta(n^{3/2})$:

In [ ]:
#Kevin Alexis Iturra Carreño
def ShellSort(a):
  """Ordena a usando Shell Sort, con la secuencia de valores …,63,31,15,7,3,1"""
  # Escriba aquí el código para invocar d_ordena_insercion reiteradamente
  # con la secuencia de valores indicada
  #Le asignamos una variable al largo de nuestro arreglo
  n=len(a)
  #Asignamos otra variable al incremento seleccionado, nuestro caso el de Hibbard
  incremento=(2**n)-1
  #Para todos los numeros entre 0 y el largo de el arreglo queremos que nos llame a la funcion d_ordena_insercion
  for i in range(0,n):
    d_ordena_insercion(a,incremento)
    #Divide en 2 el resultado y nos entregue la parte entera
    incremento//=2

Pruebe aquí su algoritmo de la manera siguiente:

In [ ]:
A = np.array([46,35,95,21,82,70,72,56,64,50])
ShellSort(A)
print(A)
verifica_d_ordenado(A,1)

[21 35 46 50 56 64 70 72 82 95]
Arreglo 1-ordenado OK.


En la siguiente celda agregue una prueba similar de ordenación de un arreglo de tamaño $1000$ generado al azar (sin imprimirlo):

In [ ]:
#Kevin Alexis Iturra Carreño
#importamos random para generar al azar un arreglo de tamaño 1000
import random
#Crea un arreglo vacío
L=[]
#Para todos los numeros desde 0 hasta el 1000
for i in range(1000):
  #Genera al azar 1000 numeros
  r=random.randint(0,1000)
  #Los agrega al arreglo
  L.append(r)
  #Llama a la función ShellSort
ShellSort(L)
#Imprime el arreglo ordenado
print(L)
#verificamos la función
verifica_d_ordenado(L,511)
verifica_d_ordenado(L,255)
verifica_d_ordenado(L,127)
verifica_d_ordenado(L,63)
verifica_d_ordenado(L,31)
verifica_d_ordenado(L,15)
verifica_d_ordenado(L,7)
verifica_d_ordenado(L,3)
verifica_d_ordenado(L,1)

[0, 2, 3, 4, 5, 7, 7, 8, 8, 9, 9, 11, 13, 16, 16, 18, 19, 19, 21, 21, 21, 23, 23, 23, 24, 24, 25, 25, 27, 28, 28, 29, 30, 32, 34, 34, 34, 35, 35, 35, 35, 36, 36, 40, 40, 41, 42, 42, 42, 45, 46, 47, 47, 51, 52, 53, 54, 57, 58, 58, 59, 60, 61, 65, 66, 66, 66, 67, 67, 69, 74, 75, 76, 77, 78, 80, 83, 83, 83, 84, 87, 88, 88, 89, 89, 91, 92, 93, 95, 95, 96, 96, 97, 98, 98, 98, 99, 100, 101, 104, 105, 106, 107, 108, 109, 111, 114, 115, 115, 115, 116, 117, 117, 117, 118, 118, 118, 120, 120, 120, 123, 123, 124, 124, 124, 126, 126, 127, 128, 129, 129, 130, 133, 134, 134, 134, 135, 138, 139, 142, 143, 144, 145, 147, 148, 148, 148, 148, 149, 152, 152, 153, 154, 155, 155, 155, 155, 157, 159, 159, 160, 160, 160, 160, 160, 161, 162, 164, 165, 166, 167, 167, 169, 169, 170, 174, 174, 175, 175, 175, 176, 177, 178, 179, 179, 183, 184, 184, 186, 187, 188, 188, 190, 190, 190, 192, 193, 194, 194, 196, 196, 197, 198, 198, 198, 198, 199, 200, 200, 200, 201, 201, 202, 205, 206, 208, 208, 209, 209, 209, 211, 21

## 3) Probar con una secuencia diferente de valores $d_k$

Finalmente, investigue respecto de otras maneras de generar la secuencia $d_k$, escoja una secuencia en particular, modifique su versión de Shellsort que la use y pruébela.

In [ ]:
#Kevin Alexis Iturra Carreño
def Shellsort(a):
  """Ordena a usando Shell Sort, con la secuencia de valores …,364,121,40,13,4,1,0(Secuencia de Knuth) [(3^n)-1]/2"""
  #La fórmula de la secuecnia utilizada fue sacada de https://en.wikipedia.org/wiki/Shellsort en el apartado gap sequences
  #Cabe recalcar que las modificaciones que se le hizo al anterior ShellSort son mínimas por lo que los códigos son muy similares.
  #Escriba aquí el código para invocar d_ordena_insercion reiteradamente
  # con la secuencia de valores indicada
  #Le asignamos una variable al largo de nuestro arreglo
  n=len(a)
  #Asignamos otra variable al incremento seleccionado, nuestro caso el de Knuth
  incremento=((3**n)-1)//2
  #Para todos los numeros entre 0 y el largo de el arreglo queremos que nos llame a la funcion d_ordena_insercion
  for i in range(0,n):
    d_ordena_insercion(a,incremento)
    #Divide en 3 el resultado y nos entregue la parte entera
    incremento//=3 

In [ ]:
A = np.array([40,35,91,29,86,70,77,55,4,50])
Shellsort(A)
print(A)
verifica_d_ordenado(A,7)
verifica_d_ordenado(A,3)
verifica_d_ordenado(A,1)

[ 4 29 35 40 50 55 70 77 86 91]
Arreglo 7-ordenado OK.
Arreglo 3-ordenado OK.
Arreglo 1-ordenado OK.


## ¿Qué hay que entregar?

Usted debe entregar este mismo archivo, modificado de acuerdo a lo que se pide. Haga todos los cambios necesarios para explicar y documentar adecuadamente su código. Cite todas las fuentes de información utilizadas. **No olvide poner su nombre en el encabezamiento**.